"""Initial migration or added columns

Revision ID: 31d832b7b1bb
Revises: 
Create Date: 2026-02-26 20:44:48.847481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d832b7b1bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_tests_15', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_tests_30', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_tests_60', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_tests_120', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('best_wpm_15', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('best_wpm_30', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('best_wpm_60', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('best_wpm_120', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'best_wpm_120')
    op.drop_column('users', 'best_wpm_60')
    op.drop_column('users', 'best_wpm_30')
    op.drop_column('users', 'best_wpm_15')
    op.drop_column('users', 'total_tests_120')
    op.drop_column('users', 'total_tests_60')
    op.drop_column('users', 'total_tests_30')
    op.drop_column('users', 'total_tests_15')
    # ### end Alembic commands ###
