"""Initial migration

Revision ID: 3ee5763666ec
Revises: 
Create Date: 2026-03-01 20:04:23.441604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee5763666ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('time_mode', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_wpm', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    op.add_column('test_results', sa.Column('difficulty', sa.String(), nullable=False))
    op.drop_column('users', 'total_tests_30')
    op.drop_column('users', 'total_tests_15')
    op.drop_column('users', 'best_wpm_15')
    op.drop_column('users', 'best_wpm_120')
    op.drop_column('users', 'total_tests_60')
    op.drop_column('users', 'best_wpm_60')
    op.drop_column('users', 'best_wpm_30')
    op.drop_column('users', 'total_tests_120')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_tests_120', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('best_wpm_30', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('best_wpm_60', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_tests_60', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('best_wpm_120', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('best_wpm_15', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_tests_15', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_tests_30', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('test_results', 'difficulty')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    # ### end Alembic commands ###
