"""initial

Revision ID: cede0a195bc1
Revises: 
Create Date: 2026-03-02 13:43:35.436955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cede0a195bc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('yakut_letters', sa.Integer(), sa.Computed("regexp_count(word, '[ҥҕөһү]', 1, 'i')", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'yakut_letters')
    # ### end Alembic commands ###
